- name: protocol
  addr: RAJ5CK5CO2H3KDPQYAG2RDTKE2RHCEP4PA2TKQEIY6WHYFPOZCXH4ZQEXM
  mnemonic: luxury access asthma biology file help climb subway later badge sport
    beyond sick waste picture lab ceiling property situate modify input dirt
    radar abstract laptop

- name: supplier
  addr: 76ACOKUNIB66C35TWH23O3ZTVST22Q7GUWD77PYE6RVF7ZW4TSAZRZXSAU
  mnemonic: remove wagon rally lava edge pizza text coin hawk benefit car slight
    demise obey wool scissors wrestle title gentle sure loyal grid door ability
    glue

- name: alice
  addr: B62OIM2VDBSDRH2MYKEJQ2EZDMQSEDYBFRYJVGPGUHTPQYAAQFYRAV3YXU
  mnemonic: sibling bounce develop ice dwarf pulse power impose leader glue tray
    company cook lonely hawk city run crazy review file leopard novel belt
    ability mimic

- name: bob
  addr: XR7SQ7UKLEOUNV5XY6NHPKMG2WVUEOPMCYVAMCIVTFLJ7VNHXGBQXWQRBU
  mnemonic: foam swift garden tackle stairs monitor nuclear myth jelly farm harbor
    bachelor lawsuit village fault parrot include warfare truly drill rival
    hundred omit abandon bring
